<?php View::content(); ?>
    <div class="row mx-auto" >
        <?php View::partial('menu', false,  array('activo'=>$activo)) ?>
        <div class="col-12 col-lg-8 col-xl-8 colorCajasBlancas mx-auto">
            <div class="row">
                <div class="col">
                    <h4 class="modal-title">Usuarios</h4>
                    <p class="txtsGrises">
                        En esta sección podrás realizar con la metodología de CRUD, la Creacion, Lectura, Actualizacion y eliminación de los usuarios. 
                        <span class="txtsOscurosColor">
                            <strong>Recuerda que los usuarios son perfilados</strong> 
                        </span>
                    </p>
                    <div
                        class="row">
                        <div class="col">
                            <table class="table table-responsive txtsGrises pasos">
                                <thead>
                                    <tr>
                                        <th> </th>
                                        <th>NAMES</th>
                                        <th>PHONE </th>
                                        <th class="d-none d-lg-block">E-MAIL </th>
                                        <th>OPTIONS </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($listUser->items as $item) : ?>
                                    <tr>
                                        <td><input type="checkbox"></td>
                                        <td><?= $item->firstName ?></td>
                                        <td><?= $item->phone ?></td>
                                        <td class="d-none d-lg-block"><?= $item->email ?></td>
                                        <td><button class="btn btn-primary btn-sm btn-Oscuro" type="button" data-toggle="modal" data-target="#modalOption" data-name="<?= $item->firstName ?>" data-id="<?= $item->id ?>" data-lastname="<?= $item->lastName ?>" data-phone="<?= $item->phone ?>" data-email="<?= $item->email ?>" data-active="<?= $item->active ?>"><i class="icon ion-ios-more"></i></button></td>
                                    </tr>
                                    
                                   
                                    <?php endforeach; ?>
                                    </ul>
                                 
                                </tbody>
                            </table>
                        </div>
                </div>
                <div class="row">
                    <div class="col">
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <nav class="pagination justify-content-left">
                            <ul class="pagination">
                                   <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
                                    <?php if($listUser->prev){ ?>
                                         <li class="page-item"><a class="page-link" aria-label="Previous" href="<?=APP_PAGE_OMOLDS;?>usuarios/index/<?= $listUser->prev ?>"><span aria-hidden="true">«</span></a></li>
                                    <?php } ?>
                                     <!--li class="page-item active"><a class="page-link">1</a></li-->
                                    <?php if($listUser->next){ ?>
                                         <li class="page-item"><a class="page-link" aria-label="Next" href="<?=APP_PAGE_OMOLDS;?>usuarios/index/<?= $listUser->next ?>"><span aria-hidden="true">»</span></a></li>
                                    <?php } ?>

                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="row">
                    <div class="col"><a class="btn btn-primary btn-circle btnCircular" role="button" href="<?=APP_PAGE_OMOLDS;?>usuarios/create" data-bs-hover-animate="tada">+</a></div>
                </div>
            </div>
        </div>
    </div>
    </div>


<!-- Modales -->
<div class="modal fade" id="modalOption" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" style="z-index: 1300;">
    <div class="modal-dialog modalInferior" role="document" style="max-width: 100%">
        <div class="row padMar colorCajasBlancas modalInferior">
            <div class="col modal-content">
                <div class="row">
                    <div class="col modal-header">
                        <h4 class="modal-title">Options </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col modal-body">
                        <div class="row">
                            <div class="col"><a id="viewption" href="#" data-toggle="modal" data-target="#modalView" data-name="0" data-lastname="0" data-phone="0" data-email="0" data-active="0"><i class="fa fa-eye"></i> View </a></div>
                        </div>
                        <div class="row">
                            <div class="col"><a id="editOption" href="#"><i class="icon ion-edit"></i> Edit </a></div>
                        </div>
                        <div class="row">
                            <div class="col"><a id="delOption" href="#" data-toggle="modal" data-target="#modalEliminar" data-name="0" data-id="0"><i class="fa fa-trash"></i> Delete </a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- modal-content -->
    </div><!-- modal-dialog -->
</div><!-- modal -->


<!-- Modal de borrar-->
<form id="eliminar-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>usuarios/del" class="contact-form form">
<div id="modalEliminar" class="modal fade" role="dialog">
  <div class="modal-dialog" style="width:60%;">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Borrar </h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p>Estas seguro de eliminar el usuario</p>
      </div>
      <div class="modal-footer">
        <input type="hidden" name="user_om_id" id="user_om_id"  required="required">
        <div class="row">
          <div class="col-12">
            <div class="col-md-6"><button type="submit" class="btn btn-primary btn-Oscuro">DELETE</button></div>
       
          </div>
        </div>
        
      </div>
    </div>
  </div>
</div>
</form>

<div class="modal fade centro" role="dialog" tabindex="-1" id="modalView">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title txtsGrises">VIEW </h6><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button></div>
            <div class="modal-body">
                <h2 class="titulos">User</h2>
                <p class="text-left margenesEspacio">Write your information to be part of our community and have access to the system. </p>
                <div class="col padMar">
                    <input type="text" id="vw_firstName" value="Name" class="margenesEspacio inputLargo" disabled>
                    <input type="text" id="vw_lastName" value="Lastname" class="margenesEspacio inputLargo" disabled>
                    <input type="text" id="vw_email" value="Email " class="margenesEspacio inputLargo" disabled>
                    <input type="text" id="vw_phone" value="Create" class="margenesEspacio inputLargo" disabled>
                    <input type="text" id="vw_active" value="Mobile" class="margenesEspacio inputLargo"disabled>
                </div>
            </div>
           
        </div>
    </div>
</div>

<script type="text/javascript">
$('#modalOption').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id = button.data('id');
  var name = button.data('name');
  var lastname = button.data('lastname');
  var phone = button.data('phone');
  var email = button.data('email');
  var active = button.data('active');
  var modal = $(this)
  modal.find('.modal-title').text('Options for ' + name);
  modal.find('#editOption').attr("href", "<?=APP_PAGE_OMOLDS;?>usuarios/edit/"+id);
  modal.find('#delOption').data("id", id);
  modal.find('#delOption').data("name", name);

  modal.find('#viewption').data("id", id);
  modal.find('#viewption').data("name", name);
  modal.find('#viewption').data("lastname", lastname);
  modal.find('#viewption').data("phone", phone);
  modal.find('#viewption').data("email", email);
  modal.find('#viewption').data("active", active);
});

$('#modalView').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id = button.data('id');
  var name = button.data('name');
  var lastname = button.data('lastname');
  var email = button.data('email');
  var active = button.data('active');
  var modal = $(this);
  modal.find('.modal-title').text('View for ' + name);
  modal.find('#vw_firstName').val(name);
  modal.find('#vw_lastName').val(lastname);
  modal.find('#vw_email').val(email);
  modal.find('#vw_active').val(active);

  
  $('#modalOption').modal('hide');
});

$('#modalEliminar').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id = button.data('id');
  var name = button.data('name');
  var modal = $(this)
  modal.find('.modal-title').text('Delete for ' + name);
  modal.find('#user_om_id').val(id);
  $('#modalOption').modal('hide');
});
</script>