<div class="col-12 col-lg-8 col-xl-8 padMar espaciosPestanas mx-auto">
    <div class="btn-group" role="group" style="width: 100%">
    	<a class="btn btn-primary <?php if($activo == 'Usuarios'){ ?> active <?php } ?> btn-Blanco" role="button" href="<?=APP_PAGE_OMOLDS?>usuarios" data-bs-hover-animate="tada">Usuarios</a>

        <a class="btn btn-primary <?php if($activo == 'Categorias'){ ?> active <?php } ?>  btn-Blanco" role="button" href="<?=APP_PAGE_OMOLDS?>categorias" data-bs-hover-animate="tada">Categorias </a>

        <a class="btn btn-primary  btn-Blanco" role="button" href="<?=APP_PAGE_OMOLDS?>login/closeSession" data-bs-hover-animate="tada" style="position: absolute; left: 84%;" ><span class="fa fa-user btn-primary"> </span> Cerrar </a>

    </div>
</div>