<?php View::content(); ?>

<div>
        <div class="row padMar modalCompleta d-none">
            <div class="col cajaIcono"><i class="fa fa-question-circle"></i></div>
            <div class="col padMar text-center col-12 txtGrande">
                <h3>Estamos solucionando sus inquietudes, <strong>En un momento regresamos...</strong> </h3></div>
            <div class="col text-center col-12 url">
                <p>Si desea conocer más de nuestros productos visite:&nbsp;<span><a href="https://www.grupobancolombia.com/wps/portal/personas" target="_blank" class="txtsAmarillos">www.grupobancolombia.com </a></span></p>
            </div>
        </div>
        <div class="row padMar modalCompleta d-none">
            <div class="col cajaIcono"><i class="fa fa-check-square"></i></div>
            <div class="col padMar text-center col-12 txtGrande">
                <h3>¿Cómo fue su experiencia en este Video Chat?&nbsp; </h3></div>
            <div class="col text-center col-12 url">
                <button class="btn btn-primary btnClaro" type="button"><i class="fa fa-star"></i> ALTO</button>
                <button class="btn btn-primary btnClaro" type="button"><i class="fa fa-star-half-empty"></i> MEDIO</button>
                <button class="btn btn-primary btnClaro" type="button"><i class="fa fa-star-o"></i> BAJO</button>
            </div>
        </div>
        <div class="row padMar modalCompleta d-none">
            <div class="col cajaIcono"><i class="fa fa-mobile-phone"></i></div>
            <div class="col padMar text-center col-12 txtGrande">
                <h3>Accede a través de tu computador de escritorio y descubre todo lo que Bancolombia tiene para ti en nuestro nuevo Video Chat.&nbsp; </h3></div>
            <div class="col text-center col-12 urlBancolombia">
                <p>Si deseas conocer más de nuestros productos visita:&nbsp;<span><a href="https://www.grupobancolombia.com/wps/portal/personas" target="_blank" class="txtsAmarillos">www.grupobancolombia.com </a></span></p>
            </div>
        </div>
        <div class="row justify-content-center align-items-center text-center d-none">
            <div class="col col-12 modalStickers"><i class="icon ion-videocamera icon"></i>
                <p>POR FAVOR ENCIENDA SU CÁMARA EN ESTE MOMENTO</p>
                <button class="btn btn-primary btnClaro" type="button"> INICIAR</button>
            </div>
        </div>
        <div class="row padMar modalBienvenida d-none">
            <div class="col"><img src="<?= APP_PAGE_OMOLDS ?>img/logoBancolombiaMovil.png" style="width:100%;">
                <p class="padMar txtsAzules">BIENVENIDO A NUESTRO VIDEO CHAT</p>
            </div>
        </div>
        <div class="row padMar modalAyudaventas d-none">
            <div class="col"><img src="<?= APP_PAGE_OMOLDS ?>img/ayudaVentas1.jpg" style="width:100%;"></div>
        </div>
    </div>
    <div id="sombraModales" class="sombraModales d-none"></div>
    <h1 class="headerOmolds text-center d-none"> <svg class="iconProducto" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 44.2 51" style="enable-background:new 0 0 44.2 51;" xml:space="preserve">
  <path  class="hexagono" d="M22.1,0L0,12.8v25.5L22.1,51l22.1-12.8V12.8L22.1,0z M38.7,35.1l-16.6,9.6L5.5,35.1V15.9l16.6-9.6l16.6,9.6
    V35.1z"/>
</svg><span class="tituloProducto">VICH</span><span class="tituloProductoOM">om</span></h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col col-12 txtsBlancos headerAgenteMovil">
                <h6 class="padMar">Agente: Nicolas Isaza Palencia</h6></div>
            <div class="col">
                <div class="row padMar txtsChat" style="position:absolute;">
                    <div class="col-12 col-lg-8 mx-auto" style="padding: 0 2%;">
                        <p><strong>AGENTE: </strong><a href="">Buscando agentes conectados</a></p>
                        <p><strong>AGENTE: </strong>Buenos dias</p>
                        <p><strong>USUARIO:</strong> Hola</p>
                        <p><strong>AGENTE:</strong> ¿Que tal como ha estado?</p>
                        <p><strong>AGENTE:</strong> En que podemos ayudarle</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2 d-none d-md-block"></div>
                    <div class="col padMar col-xs-12 col-sm-12 col-md-12 col-lg-4 videoUsuario" style="z-index:10 !important;  border: solid 0px #fff;">
                        <img src="<?= APP_PAGE_OMOLDS ?>img/imgUsuario.png" style="width:20% !important;">
                    </div>
                    <div class="col padMar col-xs-12 col-sm-12 col-md-12 col-lg-4 videoAgente"><img class="img-fluid" src="<?= APP_PAGE_OMOLDS ?>img/imgAgente.png" style="width:100% !important;"></div>
                    <div class="col-lg-2 d-none d-md-block"></div>
                </div>
                <div class="row">
                    <div class="col-12 col-lg-8 cajaEscribaMensaje mx-auto">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Escriba su mensaje...">
                            <div class="input-group-btn">
                                <button class="btn btn-primary btnOscuro" type="button"><i class="icon ion-chatbubble"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col text-center col-12">
                <p class="txtsBlancos padMar titCalifique">En cualquier momento califique el nivel del servicio </p>
            </div>
        </div>
        <div class="row text-center margenBotones">
            <div class="col-1 col-lg-3"></div>
            <div class="col-10 col-lg-6">
                <button class="btn btn-primary btnClaro" type="button"><i class="fa fa-star"></i> ALTO</button>
                <button class="btn btn-primary btnClaro" type="button"><i class="fa fa-star-half-empty"></i> MEDIO</button>
                <button class="btn btn-primary btnClaro" type="button"><i class="fa fa-star-o"></i> BAJO</button>
            </div>
            <div class="col-1 col-lg-3"></div>
        </div>
    </div>
    <footer class="footerOmolds d-none d-md-block">
        <div class="col">
            <p>Todos los derechos reservados por <strong>© </strong><a href="http://www.omolds.com" target="_blank">www.omolds.com </a><strong>2017</strong></p>
        </div>
    </footer>