<?php View::content(); ?>

<div class="container-fluid">

        <nav class="navbar navbar-toggleable-md navbar-light vistaCliente">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <b><a class="navbar-brand" href="<?=APP_PAGE_OMOLDS;?>controlador"> VISTA CONTROLADOR / </a> <a class="navbar-brand" href="<?=APP_PAGE_OMOLDS;?>controlador/cordinadores">Coordinadores</a></b>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
               <div class="col-md-2">&nbsp;</div>
               <div class="col-md-8">
                 <form class="form-inline my-2 my-lg-0">
                  <!--input class="form-control mr-sm-2" type="text" placeholder="Buscar">
                  <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button-->
                </form>
              </div>
              <div class="col-md-2">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                     <a class="nav-link" href="<?=APP_PAGE_OMOLDS;?>login/cerrarSeccion"><b>Logout X</b></a>
                  </li>
                </ul>
              </div>
          
          </div>
        </nav>



      <div class="row conten <?= $FONDO_APP; ?>">
        <div class="col-md-2">
          <div class="row">
            <div class="col-2">&nbsp;</div>
            <div class="col-9 text-center">
             <img src="<?=$cliente->imagen ?>" class="img-responsive img-thumbnail" alt="Agente">
                <b><?= $cliente->nombre?></b>
            </div>
            <div class="col-1">&nbsp;</div>
          </div>    
        </div>

        <div class="col-md-9">
          <div class="row">
             <div class="col-md-12">
              <div class="row">
                <div class="col-md-6">
                  <h3>COORDINADORES</h3>
                </div>
                <div class="col-md-6 text-right">
                  <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#nuevoCordinador" style="margin-bottom: 5px;">Agregar coordinador</button>
                </div>
              </div>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered table-lis">
                      <thead>
                        <tr class="rojoCoral">
                          <th>Nombre</th>
                          <th>Correo electrónico</th>
                          <th>Configuración</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php foreach($cordinadores as $campos): ?>
                          <tr>
                            <th scope="row"><?=$campos->nombre; ?></th>
                            <td><?=$campos->email; ?></td>
                           <td>
                            <a class="btn bg-faded text-muted" href="#"  data-toggle="modal" data-target="#modalVer-<?=$campos->id; ?>"><i class="fa fa-eye" aria-hidden="true"></i></a>
                            <a class="btn bg-faded text-muted" href="#"  data-toggle="modal" data-target="#modalEditar-<?=$campos->id; ?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                            <a class="btn bg-faded text-muted" href="#"  data-toggle="modal" data-target="#modalEliminar-<?=$campos->id; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                          </td>
                          </tr>
                         <?php endforeach; ?>
                      </tbody>
                    </table>
                  <?php foreach($cordinadores as $campos): ?>
                      
                     <!-- Modal Ver-->
                         <div id="modalVer-<?=$campos->id; ?>" class="modal fade" role="dialog">
                      <div class="modal-dialog"  style="width:50%;">
                        <!-- Modal content-->
                        <div class="modal-content <?= $FONDO_APP; ?>">
                          <div class="modal-header rojoCoral">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><?= ($campos->nombre); ?></h4>
                          </div>

                      <div class="modal-body">
                        <div class="row">

                        
                          <div class="col-md-12">
                              <p>Nombre: <b><?=($campos->nombre); ?></b></p>                
                              <p>Celular: <b><?=($campos->celular); ?></b></p>                
                              <p>Correo electrónico: <b><?=($campos->email); ?></b></p>
                          </div>
                    
                      </div>
                
                      </div>
                        
                          
                        </div>
                      </div>
                    
                    </div>
                       
                    
                        <!-- Modal Editar-->
                        <form id="edit-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>controlador/editarCordinador" class="contact-form form" target="resUpdate<?=$campos->id; ?>">
                        <div id="modalEditar-<?=$campos->id; ?>" class="modal fade" role="dialog">
                      <div class="modal-dialog"  style="width:80%;">
                        <!-- Modal content-->
                        <div class="modal-content <?= $FONDO_APP; ?>">
                          <div class="modal-header rojoCoral">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><?= ($campos->nombre); ?></h4>
                          </div>

                      <div class="modal-body">

                        <div class="row">
             
                            <div class="col-md-12">
                              

                              <div class="form-group row margin">
                                <label for="example-text-input" class="col-2 col-form-label">Nombre:</label>
                                <div class="col-10">
                                  <input id="nombre" name="nombre" value="<?=($campos->nombre); ?>" type="text" min="3" class="form-control" data-validation="required" required>
                                </div>
                          
                                <label for="example-text-input" class="col-2 col-form-label">Celular:</label>
                                <div class="col-10">
                                    <input id="celular" name="celular"  value="<?=($campos->celular); ?>" type="number"  class="form-control" data-validation="required" required>
                                </div>
                          
                                <label for="example-text-input" class="col-2 col-form-label">Email:</label>
                                <div class="col-10">
                                     <input id="email" name="email" value="<?=($campos->email); ?>"  type="mail"  class="form-control" data-validation="required" required>
                                </div>

                                <label for="example-text-input" class="col-2 col-form-label">Clave:</label>
                                <div class="col-10">
                                     <input id="clave" name="clave"   type="password"  class="form-control" >
                                </div>         
                              </div>
                            </div>
                          </div>
                          <div class="modal-footer">
                            <input type="hidden" name="idCordinador"  value="<?=$campos->id; ?>" required="required" class="form-control"> 
                            <div class="col-md-8 col-md-offset-2 col-sm-12">
                              <iframe name="resUpdate<?=$campos->id; ?>"  style="height: 70px;  max-width: 100%; width: 100%;" frameborder="0"></iframe>
                            </div>    
                            <button type="submit" class="btn rojoCoral">Actualizar</button>
                          </div>
                      </div>
                        
                          
                        </div>
                      </div>
                    
                    </div>
                        </form>
                        
                         <!-- Modal de borrar-->
                        <form id="eliminar-alert" method="post" action="<?=APP_PAGE_OMOLDS;?>controlador/eliminarCordinador" class="contact-form form" target="resDelete<?=$campos->id; ?>">
                        <div id="modalEliminar-<?=$campos->id; ?>" class="modal fade" role="dialog">
                          <div class="modal-dialog" style="width:60%;">
                            <!-- Modal content-->
                            <div class="modal-content <?= $FONDO_APP; ?>">
                              <div class="modal-header rojoCoral">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Borrar <?= ($campos->nombre); ?></h4>
                              </div>
                              <div class="modal-body">
                                <p>Estas seguro de eliminar el coordinador</p>
                              </div>
                              <div class="modal-footer">
                                <input type="hidden" name="idCordinador" value="<?=$campos->id; ?>" required="required" class="form-control">
                                <div class="row">
                                  <div class="col-md-8">
                                    <div class="col-md-8 col-md-offset-2 col-sm-12">
                                    <iframe name="resDelete<?=$campos->id; ?>"  style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
                                     </div>
                                  </div>
                                  <div class="col-md-4">
                                    <div class="col-md-6"><button type="submit" class="btn btn-success">Borrar</button></div>
                                   
                                  </div>
                                </div>
                                
                              </div>
                            </div>
                          </div>
                        </div>
                        </form>
                  <?php endforeach; ?>
                  
                </div>    
              </div>
          </div>
          
        </div>
        <div class="col-md-1">&nbsp;</div>
      </div>

       <?php View::partial('kumbia/footer') ?>
</div>



 <div class="modal fade" id="nuevoCordinador" role="dialog" >
  <form  action="<?=APP_PAGE_OMOLDS;?>controlador/guardacordinador"  method="POST" id="my_form" target="resDataInfo">
        <div class="modal-dialog" >
        
          <!-- Modal content-->
          <div class="modal-content <?= $FONDO_APP; ?> " style="width: 600px;">
            <div class="modal-header rojoCoral">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Nuevo | Información Básica</h4>
            </div>
            <div class="modal-body">
              <div class="row">
             
                <div class="col-md-12">
                  <div class="form-group row margin">
                    <label for="example-text-input" class="col-2 col-form-label">Nombre:</label>
                    <div class="col-10">
                      <input id="nombre" name="nombre" type="text" min="3" class="form-control" data-validation="required" required>
                    </div>
              
                    <label for="example-text-input" class="col-2 col-form-label">celular:</label>
                    <div class="col-10">
                        <input id="celular" name="celular"  type="number"  class="form-control" data-validation="required" required>
                    </div>
              
                    <label for="example-text-input" class="col-2 col-form-label">Email:</label>
                    <div class="col-10">
                         <input id="email" name="email"  type="mail"  class="form-control" data-validation="required" required>
                    </div>

                    <label for="example-text-input" class="col-2 col-form-label">Clave:</label>
                    <div class="col-10">
                         <input id="clave" name="clave"  type="password"  class="form-control" data-validation="required" required>
                    </div>         
                  </div>
                </div>
              </div>
            <div class=" row">
              
                <div class="col-md-6">
                  <iframe name="resDataInfo"  style="height: auto; max-width: 100%; width: 100%;" frameborder="0"></iframe>
                </div>
                <div class="col-md-6">
                  <div class="row">
                    <div class="col-md-6"> <button type="submit" class="btn btn-success" >Guardar</button></div>
                    <div class="col-md-6"><button type="button" class="btn" data-dismiss="modal">Cerrar</button></div>
                  </div>
                </div>
              
            </div>
          </div>
          
        </div>
      </div>
   </form> 


</div>