<?php View::content(); ?>


    <div class="container">
        <h1 class="text-center titulosMargin txtsBlancos">CSS GENERATOR HELPER </h1>
        <div class="row padMar cajaOscuraConMargenes txtsBlancos text-left">
            <div class="col">
                <p>A través de este HELPER podrá personalizar el color de su APP basado en 10 colores básicos, (5) de ellos son OSCUROS y los otros (5) son su versión más CLAROS para así tener estados de botones y contrastes del color.&nbsp; </p>
                <h6 class="txtsBlancos text-left">Elige con el PICKER el color deseado o escribe el HEXADECIMAL:</h6></div>
        </div>
        <div class="row cajaClaraConMargenes">
            <div class="col padMar col-lg-6 col-sm-12">
                <h4 class="txtsAzules text-left subtitulosMargin">Colores</h4>
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <?php foreach($colores as $color): ?>
                                <div class="col-lg-12">
                                    <input type="color" placeholder="#000" id="<?= $color->id ?>" value="<?= $color->value_om ?>">
                                    <label class="col-form-label txtsAzules"> <?= $color->column_om ?> </label>
                                </div>

                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col padMar col-lg-6 d-none d-lg-block">
                <h3 class="txtsAzules text-left subtitulosMargin">Previsualización: </h3>
                <div style="overflow: auto; height: 732px; width: 620px; ">
                    <iframe id="IframeVista" src="<?= APP_PAGE_OMOLDS ?>/helpers/index" style="width: 412px; height: 620px; background-image: none; display: inline-block;" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
                </div>
            </div>
        </div>
        <!--div class="row">
            <div class="col text-center">
                <button class="btn btn-primary btnClaro" type="button">GUARDAR</button>
            </div>
        </div-->
        <div class="espacioBottom"></div>
    </div>



<script type="text/javascript">	
	$(function() {
	  $("input[type=color]").change(function(e){ 
	  	
	  	$.ajax({
	  	  method: "POST",		
		  url: "<?= APP_PAGE_OMOLDS ?>helpers/admCssSave",
		  data: { 'id_om': e.target.id, 'value_om': e.target.value }
		}).done(function(data) {
		  if(data == 0){
		  	$('#IframeVista').attr('src', "<?= APP_PAGE_OMOLDS ?>/index/vistaGenerador");
		  	IframeVista
		  }else{
            alert("Error al guardar");
            console.log({ 'id_om': e.target.id, 'value_om': e.target.value });
          }
		});
	  });
	});
</script>